riscv: Fix build against binutils 2.38
From version 2.38, binutils default to ISA spec version 20191213. This
means that the csr read/write (csrr*/csrw*) instructions and fence.i
instruction has separated from the `I` extension, become two standalone
extensions: Zicsr and Zifencei. As the Xen uses those instruction,
this causes the following build failure:

./arch/riscv/include/asm/system.h:68:
Error: unrecognized opcode `csrs sstatus,2', extension `zicsr' required

Signed-off-by: Oleksii Kurochko <oleksii.kurochko@gmail.com>